### ISSUE TITLE
Some questions about using t5-base

### ISSUE THREAD

**Issue by kwz219** [SophieHYe/RewardRepair#1]
Hi, dear author, congratulations to your great NPR system - RewardRepair, it's really novel and inspiring!
I'm working to train RewardRepair on other datasets.
I note that in your code "train.py", you are using transformers' API to load a pretrained model "t5-base" directly
` model = T5ForConditionalGeneration.from_pretrained('t5-base', output_hidden_states=True)`
However, I also find some config files from the directory `https://github.com/SophieHYe/RewardRepair/tree/master/model/RewardRepair`. I found some configs in this directory is not the same from t5-base. For example, the "d_ff" is while the "d_ff" of t5-base is 3072. Meanwhile, it seems this folder contains some configs for vocabulary.
I want to ask, If I want to train RewardRepair on other datasets, is it OK to just use a t5-base( as coded in train.py) or I must use the configs in  `https://github.com/SophieHYe/RewardRepair/tree/master/model/RewardRepair` ?

**Comment by SophieHYe** [comment]
Hi,
Yes, you can use our code on other datasets. You can update the dataset path in train.py.
