### ISSUE TITLE
Cannot find the MegaDiff-CodRep.tar.gz

### ISSUE THREAD

**Issue by happygirlzt** [SophieHYe/RewardRepair#3]
Hi @SophieHYe, thank you for open-sourcing!
However, I did not find the `MegaDiff-CodRep.tar.gz` under the `Prerequisites` section. Please kindly suggest. Thank you!

**Comment by happygirlzt** [comment]
Besides, the `pretrain.tar.gz` cannot be decompressed.
<img width="362" alt="Screenshot 2022-07-26 at 21 35 12" src="https://user-images.githubusercontent.com/15061984/181019426-393ec500-b475-49de-a879-923a85ce8b5c.png">

**Comment by Xyang1998** [comment]
same error

**Comment by SophieHYe** [comment]
Hi all, thanks for the suggestion. Please find the updated data :)
